import{r as t,j as i}from"../assets/jsx-runtime.js";import{M as N,u as P,P as T,a as A,b as S,L as O,S as k,m as $}from"./StarField.js";import{d as D,H,O as _}from"./HudNav.js";class B extends t.Component{getSnapshotBeforeUpdate(c){const e=this.props.childRef.current;if(e&&c.isPresent&&!this.props.isPresent){const n=this.props.sizeRef.current;n.height=e.offsetHeight||0,n.width=e.offsetWidth||0,n.top=e.offsetTop,n.left=e.offsetLeft}return null}componentDidUpdate(){}render(){return this.props.children}}function F({children:s,isPresent:c}){const e=t.useId(),n=t.useRef(null),C=t.useRef({width:0,height:0,top:0,left:0}),{nonce:p}=t.useContext(N);return t.useInsertionEffect(()=>{const{width:d,height:r,top:h,left:o}=C.current;if(c||!n.current||!d||!r)return;n.current.dataset.motionPopId=e;const a=document.createElement("style");return p&&(a.nonce=p),document.head.appendChild(a),a.sheet&&a.sheet.insertRule(`
          [data-motion-pop-id="${e}"] {
            position: absolute !important;
            width: ${d}px !important;
            height: ${r}px !important;
            top: ${h}px !important;
            left: ${o}px !important;
          }
        `),()=>{document.head.removeChild(a)}},[c]),i.jsx(B,{isPresent:c,childRef:n,sizeRef:C,children:t.cloneElement(s,{ref:n})})}const K=({children:s,initial:c,isPresent:e,onExitComplete:n,custom:C,presenceAffectsLayout:p,mode:d})=>{const r=P(U),h=t.useId(),o=t.useCallback(u=>{r.set(u,!0);for(const v of r.values())if(!v)return;n&&n()},[r,n]),a=t.useMemo(()=>({id:h,initial:c,isPresent:e,custom:C,onExitComplete:o,register:u=>(r.set(u,!1),()=>r.delete(u))}),p?[Math.random(),o]:[e,o]);return t.useMemo(()=>{r.forEach((u,v)=>r.set(v,!1))},[e]),t.useEffect(()=>{!e&&!r.size&&n&&n()},[e]),d==="popLayout"&&(s=i.jsx(F,{isPresent:e,children:s})),i.jsx(T.Provider,{value:a,children:s})};function U(){return new Map}const y=s=>s.key||"";function M(s){const c=[];return t.Children.forEach(s,e=>{t.isValidElement(e)&&c.push(e)}),c}const G=({children:s,custom:c,initial:e=!0,onExitComplete:n,presenceAffectsLayout:C=!0,mode:p="sync",propagate:d=!1})=>{const[r,h]=A(d),o=t.useMemo(()=>M(s),[s]),a=d&&!r?[]:o.map(y),u=t.useRef(!0),v=t.useRef(o),g=P(()=>new Map),[z,L]=t.useState(o),[x,w]=t.useState(o);S(()=>{u.current=!1,v.current=o;for(let f=0;f<x.length;f++){const l=y(x[f]);a.includes(l)?g.delete(l):g.get(l)!==!0&&g.set(l,!1)}},[x,a.length,a.join("-")]);const j=[];if(o!==z){let f=[...o];for(let l=0;l<x.length;l++){const m=x[l],E=y(m);a.includes(E)||(f.splice(l,0,m),j.push(m))}p==="wait"&&j.length&&(f=j),w(M(f)),L(o);return}const{forceRender:R}=t.useContext(O);return i.jsx(i.Fragment,{children:x.map(f=>{const l=y(f),m=d&&!r?!1:o===x||a.includes(l),E=()=>{if(g.has(l))g.set(l,!0);else return;let b=!0;g.forEach(I=>{I||(b=!1)}),b&&(R==null||R(),w(v.current),d&&(h==null||h()),n&&n())};return i.jsx(K,{isPresent:m,initial:!u.current||e?void 0:!1,custom:m?void 0:c,presenceAffectsLayout:C,mode:p,onExitComplete:m?void 0:E,children:f},l)})})};function q(){const s=D();return i.jsxs("div",{className:"min-h-screen bg-void text-offwhite selection:bg-plasma selection:text-void flex flex-col",children:[i.jsx(k,{}),i.jsx(H,{}),i.jsx("main",{className:"flex-grow pt-32 pb-12 px-4 md:px-8 relative z-10 flex flex-col",children:i.jsx(G,{mode:"wait",children:i.jsx($.div,{initial:{opacity:0,filter:"blur(10px)",scale:.98},animate:{opacity:1,filter:"blur(0px)",scale:1},exit:{opacity:0,filter:"blur(10px)",scale:1.02},transition:{duration:.4,ease:"easeInOut"},className:"flex-grow flex flex-col w-full max-w-7xl mx-auto",children:i.jsx(_,{})},s.pathname)})}),i.jsx("div",{className:"fixed bottom-4 left-4 font-mono text-[10px] text-signal/50 pointer-events-none z-50",children:"v2.0.26 // ORBITAL_STATION"}),i.jsx("div",{className:"fixed bottom-4 right-4 font-mono text-[10px] text-signal/50 pointer-events-none z-50",children:"DATA_STREAM: ENCRYPTED"})]})}export{G as A,q as L};
